name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v3

      - name: Build and test project with Gradle
        run: ./gradlew clean build

      - name: JUnit Report Action
        uses: mikepenz/action-junit-report@v3.1.0-b01
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
